# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!


# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
 telegram_token: 308414484:AAFl9g_2grQT6R3LRo_nPHNONwKX2Hn_iLA
 telegram_chat_id: 270380442


development:
  <<: *default
  secret_key_base: 3ce891e3cf9eec47cd0020efddb7c61d3af8f25e73b857a5562118d12fa8778784622ebb9b6b6cf7956bf4da4d4466ed53f25afc6ee76369f5335c7eb5f0fa37

test:
  <<: *default
  secret_key_base: b7c514ec8f412c59fd88009f3ff0ad0a43c45cfa78bd67b16036aa028e4257dcc7928c7631d607662aee095458166daaad2d37348862b1d53b33c2cb38e5ca00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
